name: Cleanup Workflow Runs

on:
   workflow_dispatch:
#  schedule:
#     - cron: '0 0 * * *'  # 每天运行

jobs:
  cleanup:
    runs-on: ubuntu-latest
#    permissions:
#      actions: write  # 关键权限
#      contents: read
    steps:
      - name: Delete old runs
        uses: c-hive/gha-remove-workflow-runs@v1
        with:
          repo: xkgg/OpenWrt
#          token: ${{ secrets.REPO_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          keep_days: 0
          keep_minimum: 3
          workflow_run_status: completed
          preserve_artifacts: false


